ACHIEVEMENTS = [
    # Learning Category
    {
        "id": "ach_first_lesson",
        "code": "FIRST_LESSON",
        "name": "First Steps",
        "description": "Complete your very first language lesson.",
        "icon": "👣",
        "category": "learning",
        "requirement_type": "lessons_completed",
        "requirement_value": 1,
        "course_id": None,
        "rarity": "common",
        "xp_reward": 10,
    },
    {
        "id": "ach_first_skill",
        "code": "FIRST_SKILL",
        "name": "Skill Starter",
        "description": "Master all lessons in your first skill.",
        "icon": "🎓",
        "category": "learning",
        "requirement_type": "skills_completed",
        "requirement_value": 1,
        "course_id": None,
        "rarity": "common",
        "xp_reward": 15,
    },
    {
        "id": "ach_10_lessons",
        "code": "10_LESSONS",
        "name": "Dedicated Learner",
        "description": "Complete 10 lessons across any course.",
        "icon": "📚",
        "category": "learning",
        "requirement_type": "lessons_completed",
        "requirement_value": 10,
        "course_id": None,
        "rarity": "common",
        "xp_reward": 20,
    },
    {
        "id": "ach_25_lessons",
        "code": "25_LESSONS",
        "name": "Scholar in Training",
        "description": "Complete 25 lessons across any course.",
        "icon": "📖",
        "category": "learning",
        "requirement_type": "lessons_completed",
        "requirement_value": 25,
        "course_id": None,
        "rarity": "rare",
        "xp_reward": 30,
    },
    {
        "id": "ach_50_lessons",
        "code": "50_LESSONS",
        "name": "Master Student",
        "description": "Complete 50 lessons across any course.",
        "icon": "🏅",
        "category": "learning",
        "requirement_type": "lessons_completed",
        "requirement_value": 50,
        "course_id": None,
        "rarity": "epic",
        "xp_reward": 50,
    },
    {
        "id": "ach_100_lessons",
        "code": "100_LESSONS",
        "name": "Polyglot Legend",
        "description": "Complete 100 lessons across any course.",
        "icon": "🏛️",
        "category": "learning",
        "requirement_type": "lessons_completed",
        "requirement_value": 100,
        "course_id": None,
        "rarity": "legendary",
        "xp_reward": 100,
    },

    # XP Category
    {
        "id": "ach_100_xp",
        "code": "100_XP",
        "name": "Century Scholar",
        "description": "Earn a total of 100 XP.",
        "icon": "⭐",
        "category": "xp",
        "requirement_type": "total_xp",
        "requirement_value": 100,
        "course_id": None,
        "rarity": "common",
        "xp_reward": 10,
    },
    {
        "id": "ach_500_xp",
        "code": "500_XP",
        "name": "XP Crusader",
        "description": "Earn a total of 500 XP.",
        "icon": "🌟",
        "category": "xp",
        "requirement_type": "total_xp",
        "requirement_value": 500,
        "course_id": None,
        "rarity": "rare",
        "xp_reward": 25,
    },
    {
        "id": "ach_1000_xp",
        "code": "1000_XP",
        "name": "Millennium Master",
        "description": "Earn a total of 1,000 XP.",
        "icon": "💫",
        "category": "xp",
        "requirement_type": "total_xp",
        "requirement_value": 1000,
        "course_id": None,
        "rarity": "epic",
        "xp_reward": 50,
    },
    {
        "id": "ach_2500_xp",
        "code": "2500_XP",
        "name": "XP Titan",
        "description": "Earn a total of 2,500 XP.",
        "icon": "✨",
        "category": "xp",
        "requirement_type": "total_xp",
        "requirement_value": 2500,
        "course_id": None,
        "rarity": "epic",
        "xp_reward": 75,
    },
    {
        "id": "ach_5000_xp",
        "code": "5000_XP",
        "name": "Grandmaster of Knowledge",
        "description": "Earn a total of 5,000 XP.",
        "icon": "💎",
        "category": "xp",
        "requirement_type": "total_xp",
        "requirement_value": 5000,
        "course_id": None,
        "rarity": "legendary",
        "xp_reward": 150,
    },

    # Streak Category
    {
        "id": "ach_3_day_streak",
        "code": "3_DAY_STREAK",
        "name": "Spark of Consistency",
        "description": "Maintain a learning streak for 3 consecutive days.",
        "icon": "⚡",
        "category": "streak",
        "requirement_type": "streak",
        "requirement_value": 3,
        "course_id": None,
        "rarity": "common",
        "xp_reward": 15,
    },
    {
        "id": "ach_7_day_streak",
        "code": "7_DAY_STREAK",
        "name": "Week Warrior",
        "description": "Maintain a learning streak for 7 consecutive days.",
        "icon": "🔥",
        "category": "streak",
        "requirement_type": "streak",
        "requirement_value": 7,
        "course_id": None,
        "rarity": "rare",
        "xp_reward": 30,
    },
    {
        "id": "ach_14_day_streak",
        "code": "14_DAY_STREAK",
        "name": "Fortnight Flame",
        "description": "Maintain a learning streak for 14 consecutive days.",
        "icon": "💥",
        "category": "streak",
        "requirement_type": "streak",
        "requirement_value": 14,
        "course_id": None,
        "rarity": "rare",
        "xp_reward": 50,
    },
    {
        "id": "ach_30_day_streak",
        "code": "30_DAY_STREAK",
        "name": "Monthly Monarch",
        "description": "Maintain a learning streak for 30 consecutive days.",
        "icon": "👑",
        "category": "streak",
        "requirement_type": "streak",
        "requirement_value": 30,
        "course_id": None,
        "rarity": "epic",
        "xp_reward": 100,
    },
    {
        "id": "ach_60_day_streak",
        "code": "60_DAY_STREAK",
        "name": "Streak Champion",
        "description": "Maintain a learning streak for 60 consecutive days.",
        "icon": "🏆",
        "category": "streak",
        "requirement_type": "streak",
        "requirement_value": 60,
        "course_id": None,
        "rarity": "legendary",
        "xp_reward": 200,
    },

    # Mastery Category
    {
        "id": "ach_first_skill_mastered",
        "code": "FIRST_SKILL_MASTERED",
        "name": "Crown Collector",
        "description": "Master your very first skill to 100%.",
        "icon": "👑",
        "category": "mastery",
        "requirement_type": "skills_completed",
        "requirement_value": 1,
        "course_id": None,
        "rarity": "common",
        "xp_reward": 20,
    },
    {
        "id": "ach_5_skills_mastered",
        "code": "5_SKILLS_MASTERED",
        "name": "Mastery Adept",
        "description": "Master 5 skills across any course.",
        "icon": "🎯",
        "category": "mastery",
        "requirement_type": "skills_completed",
        "requirement_value": 5,
        "course_id": None,
        "rarity": "rare",
        "xp_reward": 40,
    },
    {
        "id": "ach_10_skills_mastered",
        "code": "10_SKILLS_MASTERED",
        "name": "Mastery Expert",
        "description": "Master 10 skills across any course.",
        "icon": "🔮",
        "category": "mastery",
        "requirement_type": "skills_completed",
        "requirement_value": 10,
        "course_id": None,
        "rarity": "epic",
        "xp_reward": 75,
    },
    {
        "id": "ach_first_unit_mastered",
        "code": "FIRST_UNIT_MASTERED",
        "name": "Unit Conqueror",
        "description": "Complete all skills in a single unit.",
        "icon": "🏆",
        "category": "mastery",
        "requirement_type": "units_completed",
        "requirement_value": 1,
        "course_id": None,
        "rarity": "rare",
        "xp_reward": 50,
    },
    {
        "id": "ach_3_units_mastered",
        "code": "3_UNITS_MASTERED",
        "name": "Unit Mastermind",
        "description": "Complete all skills in 3 units.",
        "icon": "🏅",
        "category": "mastery",
        "requirement_type": "units_completed",
        "requirement_value": 3,
        "course_id": None,
        "rarity": "epic",
        "xp_reward": 100,
    },

    # Course Category (Course-Aware)
    {
        "id": "ach_english_beginner",
        "code": "ENGLISH_BEGINNER",
        "name": "English Explorer",
        "description": "Complete 3 skills in the English flagship course.",
        "icon": "🇬🇧",
        "category": "course",
        "requirement_type": "course_skills_completed",
        "requirement_value": 3,
        "course_id": "crs_english",
        "rarity": "common",
        "xp_reward": 25,
    },
    {
        "id": "ach_english_master",
        "code": "ENGLISH_MASTER",
        "name": "English Master",
        "description": "Master all 8 units in the English flagship course.",
        "icon": "🎓",
        "category": "course",
        "requirement_type": "course_completed",
        "requirement_value": 1,
        "course_id": "crs_english",
        "rarity": "legendary",
        "xp_reward": 200,
    },
    {
        "id": "ach_spanish_beginner",
        "code": "SPANISH_BEGINNER",
        "name": "Spanish Explorer",
        "description": "Complete 3 skills in the Spanish course.",
        "icon": "🇪🇸",
        "category": "course",
        "requirement_type": "course_skills_completed",
        "requirement_value": 3,
        "course_id": "crs_spanish",
        "rarity": "common",
        "xp_reward": 25,
    },
    {
        "id": "ach_spanish_master",
        "code": "SPANISH_MASTER",
        "name": "Spanish Master",
        "description": "Master all 5 units in the Spanish course.",
        "icon": "💃",
        "category": "course",
        "requirement_type": "course_completed",
        "requirement_value": 1,
        "course_id": "crs_spanish",
        "rarity": "legendary",
        "xp_reward": 200,
    },
    {
        "id": "ach_french_beginner",
        "code": "FRENCH_BEGINNER",
        "name": "French Explorer",
        "description": "Complete 3 skills in the French course.",
        "icon": "🇫🇷",
        "category": "course",
        "requirement_type": "course_skills_completed",
        "requirement_value": 3,
        "course_id": "crs_french",
        "rarity": "common",
        "xp_reward": 25,
    },
    {
        "id": "ach_french_master",
        "code": "FRENCH_MASTER",
        "name": "French Master",
        "description": "Master all 3 units in the French course.",
        "icon": "🥐",
        "category": "course",
        "requirement_type": "course_completed",
        "requirement_value": 1,
        "course_id": "crs_french",
        "rarity": "legendary",
        "xp_reward": 200,
    },

    # Review Category
    {
        "id": "ach_first_review",
        "code": "FIRST_REVIEW",
        "name": "Smart Reviewer",
        "description": "Complete your first Smart Review session.",
        "icon": "🔁",
        "category": "review",
        "requirement_type": "reviews_completed",
        "requirement_value": 1,
        "course_id": None,
        "rarity": "common",
        "xp_reward": 15,
    },
    {
        "id": "ach_10_reviews",
        "code": "10_REVIEWS",
        "name": "Memory Guardian",
        "description": "Complete 10 Smart Review sessions.",
        "icon": "🛡️",
        "category": "review",
        "requirement_type": "reviews_completed",
        "requirement_value": 10,
        "course_id": None,
        "rarity": "rare",
        "xp_reward": 50,
    },
]
