"""
English Course Catalog — CourseSpec definition (FLAGSHIP COURSE).

Source language: hi (Hindi — learner's base language)
Target language: en (English)

English is the primary/flagship course:
  - 8 Units
  - 32 Skills (4 skills per unit)
  - 96 Lessons (3 lessons per skill: Learn, Practice, Mastery)
  - ~576 Exercises (6 exercises per lesson)

Note on language direction:
    source_language = "hi"  (Hindi speakers learning English)
    target_language = "en"
    In exercises: "prompt/target" = English, "source" = Hindi translation
"""

from seed.generators import CourseSpec, UnitSpec, SkillSpec, VocabItem, SentenceItem

ENGLISH_COURSE_SPEC = CourseSpec(
    id="crs_english",
    name="English",
    code="en",
    source_language="hi",
    target_language="en",
    description="Learn English from Hindi — foundations, daily life, real-world conversation, and advanced fluency.",
    units=[
        # ─────────────────────────────────────────────────────────────
        # UNIT 1 — Foundations
        # ─────────────────────────────────────────────────────────────
        UnitSpec(
            id="unit_en_01",
            title="Unit 1: Foundations",
            description="Master basic greetings, introductions, pronouns, and essential verbs.",
            order_index=1,
            skills=[
                SkillSpec(
                    id="skill_en_greetings",
                    title="Greetings",
                    description="Say hello, goodbye, and polite expressions.",
                    objective="Learner can greet others and exchange polite expressions in English.",
                    difficulty=1,
                    order_index=1,
                    xp_reward=15,
                    prerequisite_skill_id=None,
                    vocabulary=[
                        VocabItem("Hello", "नमस्ते", hint="H____"),
                        VocabItem("Good morning", "सुप्रभात", hint="G___ m______"),
                        VocabItem("Good evening", "शुभ संध्या", hint="G___ e______"),
                        VocabItem("Goodbye", "अलविदा", hint="G_____"),
                        VocabItem("Thank you", "धन्यवाद", hint="T____ y__"),
                        VocabItem("Please", "कृपया", hint="P_____"),
                        VocabItem("Sorry", "माफ़ करें", hint="S____"),
                        VocabItem("You're welcome", "आपका स्वागत है", hint="Y_____"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="Hello, how are you?",
                            source="नमस्ते, आप कैसे हैं?",
                            words=["Hello", "how", "are", "you"],
                            blank_word="Hello",
                            blank_before="",
                            blank_after=", how are you?",
                        ),
                        SentenceItem(
                            target="Good morning, nice to meet you.",
                            source="सुप्रभात, आपसे मिलकर अच्छा लगा।",
                            words=["Good", "morning", "nice", "to", "meet", "you"],
                        ),
                        SentenceItem(
                            target="Thank you very much.",
                            source="बहुत धन्यवाद।",
                            words=["Thank", "you", "very", "much"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_introductions",
                    title="Introductions",
                    description="Introduce yourself, your name, and where you are from.",
                    objective="Learner can state their name, origin, and introduce friends.",
                    difficulty=1,
                    order_index=2,
                    xp_reward=15,
                    prerequisite_skill_id="skill_en_greetings",
                    vocabulary=[
                        VocabItem("My name is", "मेरा नाम है", hint="M_ n___ i_"),
                        VocabItem("I am from", "मैं से हूँ", hint="I a_ f___"),
                        VocabItem("India", "भारत", hint="I____"),
                        VocabItem("friend", "दोस्त", hint="f_____"),
                        VocabItem("nice to meet you", "आपसे मिलकर खुशी हुई", hint="n___ t_ m___ y__"),
                        VocabItem("what is your name", "आपका नाम क्या है", hint="w___ i_ y___ n___"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="My name is Rahul.",
                            source="मेरा नाम राहुल है।",
                            words=["My", "name", "is", "Rahul"],
                            blank_word="name",
                            blank_before="My",
                            blank_after="is Rahul.",
                        ),
                        SentenceItem(
                            target="I am from India.",
                            source="मैं भारत से हूँ।",
                            words=["I", "am", "from", "India"],
                        ),
                        SentenceItem(
                            target="This is my friend Priya.",
                            source="यह मेरी दोस्त प्रिया है।",
                            words=["This", "is", "my", "friend", "Priya"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_pronouns",
                    title="Pronouns",
                    description="Personal pronouns: I, you, he, she, we, they.",
                    objective="Learner can correctly identify and use personal pronouns.",
                    difficulty=1,
                    order_index=3,
                    xp_reward=15,
                    prerequisite_skill_id="skill_en_introductions",
                    vocabulary=[
                        VocabItem("I", "मैं", hint="I"),
                        VocabItem("You", "आप/तुम", hint="Y__"),
                        VocabItem("He", "वह (पुरुष)", hint="H_"),
                        VocabItem("She", "वह (स्त्री)", hint="S__"),
                        VocabItem("We", "हम", hint="W_"),
                        VocabItem("They", "वे", hint="T___"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I am a student.",
                            source="मैं एक छात्र हूँ।",
                            words=["I", "am", "a", "student"],
                            blank_word="I",
                            blank_before="",
                            blank_after="am a student.",
                        ),
                        SentenceItem(
                            target="She is a doctor.",
                            source="वह एक डॉक्टर है।",
                            words=["She", "is", "a", "doctor"],
                        ),
                        SentenceItem(
                            target="We are learning English.",
                            source="हम अंग्रेज़ी सीख रहे हैं।",
                            words=["We", "are", "learning", "English"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_basic_verbs",
                    title="Basic Verbs",
                    description="Essential verbs: be, have, do, go, come, see.",
                    objective="Learner can use simple present verbs to describe core actions.",
                    difficulty=1,
                    order_index=4,
                    xp_reward=15,
                    prerequisite_skill_id="skill_en_pronouns",
                    vocabulary=[
                        VocabItem("be / is / am / are", "होना / है", hint="b_"),
                        VocabItem("have / has", "पास होना", hint="h___"),
                        VocabItem("do", "करना", hint="d_"),
                        VocabItem("go", "जाना", hint="g_"),
                        VocabItem("come", "आना", hint="c___"),
                        VocabItem("see", "देखना", hint="s__"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I have a book.",
                            source="मेरे पास एक किताब है।",
                            words=["I", "have", "a", "book"],
                            blank_word="have",
                            blank_before="I",
                            blank_after="a book.",
                        ),
                        SentenceItem(
                            target="We go to school.",
                            source="हम स्कूल जाते हैं।",
                            words=["We", "go", "to", "school"],
                        ),
                        SentenceItem(
                            target="They see the movie.",
                            source="वे फ़िल्म देखते हैं।",
                            words=["They", "see", "the", "movie"],
                        ),
                    ],
                ),
            ],
        ),
        # ─────────────────────────────────────────────────────────────
        # UNIT 2 — Everyday Life
        # ─────────────────────────────────────────────────────────────
        UnitSpec(
            id="unit_en_02",
            title="Unit 2: Everyday Life",
            description="Discuss family members, home environment, meals, and daily routines.",
            order_index=2,
            skills=[
                SkillSpec(
                    id="skill_en_family",
                    title="Family",
                    description="Mother, father, brother, sister, children.",
                    objective="Learner can talk about family members and relationships.",
                    difficulty=2,
                    order_index=1,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_basic_verbs",
                    vocabulary=[
                        VocabItem("father", "पिता", hint="f_____"),
                        VocabItem("mother", "माता", hint="m_____"),
                        VocabItem("brother", "भाई", hint="b______"),
                        VocabItem("sister", "बहन", hint="s_____"),
                        VocabItem("son", "बेटा", hint="s__"),
                        VocabItem("daughter", "बेटी", hint="d_______"),
                        VocabItem("family", "परिवार", hint="f_____"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="My mother is very kind.",
                            source="मेरी माता जी बहुत दयालु हैं।",
                            words=["My", "mother", "is", "very", "kind"],
                            blank_word="mother",
                            blank_before="My",
                            blank_after="is very kind.",
                        ),
                        SentenceItem(
                            target="I have one brother and one sister.",
                            source="मेरा एक भाई और एक बहन है।",
                            words=["I", "have", "one", "brother", "and", "one", "sister"],
                        ),
                        SentenceItem(
                            target="We love our family.",
                            source="हम अपने परिवार से प्यार करते हैं।",
                            words=["We", "love", "our", "family"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_home",
                    title="Home",
                    description="House, room, kitchen, bed, table, door.",
                    objective="Learner can describe items and rooms inside a house.",
                    difficulty=2,
                    order_index=2,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_family",
                    vocabulary=[
                        VocabItem("house", "घर", hint="h____"),
                        VocabItem("room", "कमरा", hint="r___"),
                        VocabItem("kitchen", "रसोई", hint="k______"),
                        VocabItem("bed", "बिस्तर", hint="b__"),
                        VocabItem("table", "मेज", hint="t____"),
                        VocabItem("door", "दरवाज़ा", hint="d___"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="This is my clean room.",
                            source="यह मेरा साफ़ कमरा है।",
                            words=["This", "is", "my", "clean", "room"],
                            blank_word="room",
                            blank_before="This is my clean",
                            blank_after=".",
                        ),
                        SentenceItem(
                            target="The food is on the table.",
                            source="खाना मेज पर है।",
                            words=["The", "food", "is", "on", "the", "table"],
                        ),
                        SentenceItem(
                            target="Please close the door.",
                            source="कृपया दरवाज़ा बंद करें।",
                            words=["Please", "close", "the", "door"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_food",
                    title="Food & Drinks",
                    description="Breakfast, lunch, dinner, water, tea, bread, rice.",
                    objective="Learner can identify meals, food items, and drinks.",
                    difficulty=2,
                    order_index=3,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_home",
                    vocabulary=[
                        VocabItem("breakfast", "नाश्ता", hint="b________"),
                        VocabItem("lunch", "दोपहर का खाना", hint="l____"),
                        VocabItem("dinner", "रात का खाना", hint="d_____"),
                        VocabItem("water", "पानी", hint="w____"),
                        VocabItem("tea", "चाय", hint="t__"),
                        VocabItem("rice", "चावल", hint="r___"),
                        VocabItem("bread", "रोटी/ब्रेड", hint="b____"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I eat breakfast every morning.",
                            source="मैं हर सुबह नाश्ता करता हूँ।",
                            words=["I", "eat", "breakfast", "every", "morning"],
                            blank_word="breakfast",
                            blank_before="I eat",
                            blank_after="every morning.",
                        ),
                        SentenceItem(
                            target="Please give me a glass of water.",
                            source="कृपया मुझे एक गिलास पानी दें।",
                            words=["Please", "give", "me", "a", "glass", "of", "water"],
                        ),
                        SentenceItem(
                            target="We drink tea in the afternoon.",
                            source="हम दोपहर में चाय पीते हैं।",
                            words=["We", "drink", "tea", "in", "the", "afternoon"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_routine",
                    title="Daily Routine",
                    description="Wake up, wash, work, study, sleep.",
                    objective="Learner can describe their daily morning and evening schedule.",
                    difficulty=2,
                    order_index=4,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_food",
                    vocabulary=[
                        VocabItem("wake up", "उठना", hint="w___ u_"),
                        VocabItem("wash", "धोना/साफ़ करना", hint="w___"),
                        VocabItem("work", "काम करना", hint="w___"),
                        VocabItem("study", "पढ़ाई करना", hint="s____"),
                        VocabItem("sleep", "सोना", hint="s____"),
                        VocabItem("every day", "हर दिन", hint="e____ d__"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I wake up early at 6 AM.",
                            source="मैं सुबह 6 बजे जल्दी उठता हूँ।",
                            words=["I", "wake", "up", "early", "at", "6", "AM"],
                            blank_word="wake",
                            blank_before="I",
                            blank_after="up early at 6 AM.",
                        ),
                        SentenceItem(
                            target="He works from home.",
                            source="वह घर से काम करता है।",
                            words=["He", "works", "from", "home"],
                        ),
                        SentenceItem(
                            target="They sleep at 10 PM.",
                            source="वे रात 10 बजे सोते हैं।",
                            words=["They", "sleep", "at", "10", "PM"],
                        ),
                    ],
                ),
            ],
        ),
        # ─────────────────────────────────────────────────────────────
        # UNIT 3 — Communication
        # ─────────────────────────────────────────────────────────────
        UnitSpec(
            id="unit_en_03",
            title="Unit 3: Communication",
            description="Formulate question words, ask for directions, state time/dates, and use common idioms.",
            order_index=3,
            skills=[
                SkillSpec(
                    id="skill_en_questions",
                    title="Questions",
                    description="What, where, when, why, who, how.",
                    objective="Learner can ask basic WH-questions in English.",
                    difficulty=3,
                    order_index=1,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_routine",
                    vocabulary=[
                        VocabItem("What", "क्या", hint="W___"),
                        VocabItem("Where", "कहाँ", hint="W____"),
                        VocabItem("When", "कब", hint="W___"),
                        VocabItem("Why", "क्यों", hint="W__"),
                        VocabItem("Who", "कौन", hint="W__"),
                        VocabItem("How", "कैसे", hint="H__"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="What is your name?",
                            source="आपका नाम क्या है?",
                            words=["What", "is", "your", "name"],
                            blank_word="What",
                            blank_before="",
                            blank_after="is your name?",
                        ),
                        SentenceItem(
                            target="Where do you live?",
                            source="आप कहाँ रहते हैं?",
                            words=["Where", "do", "you", "live"],
                        ),
                        SentenceItem(
                            target="Why are you happy?",
                            source="आप क्यों खुश हैं?",
                            words=["Why", "are", "you", "happy"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_directions",
                    title="Directions",
                    description="Left, right, straight, near, far, opposite.",
                    objective="Learner can ask for and understand navigational directions.",
                    difficulty=3,
                    order_index=2,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_questions",
                    vocabulary=[
                        VocabItem("left", "बाएँ", hint="l___"),
                        VocabItem("right", "दाएँ", hint="r____"),
                        VocabItem("straight", "सीधा", hint="s_______"),
                        VocabItem("near", "पास", hint="n___"),
                        VocabItem("far", "दूर", hint="f__"),
                        VocabItem("opposite", "सामने", hint="o_______"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="Turn left at the corner.",
                            source="मोड़ पर बाएँ मुड़ें।",
                            words=["Turn", "left", "at", "the", "corner"],
                            blank_word="left",
                            blank_before="Turn",
                            blank_after="at the corner.",
                        ),
                        SentenceItem(
                            target="Go straight ahead.",
                            source="सीधे आगे बढ़ें।",
                            words=["Go", "straight", "ahead"],
                        ),
                        SentenceItem(
                            target="The hotel is near the station.",
                            source="होटल स्टेशन के पास है।",
                            words=["The", "hotel", "is", "near", "the", "station"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_time",
                    title="Time & Dates",
                    description="Hours, days of week, months, yesterday, tomorrow.",
                    objective="Learner can tell the time, state dates, and schedule meetings.",
                    difficulty=3,
                    order_index=3,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_directions",
                    vocabulary=[
                        VocabItem("clock / time", "समय / घड़ी", hint="t___"),
                        VocabItem("Monday", "सोमवार", hint="M_____"),
                        VocabItem("today", "आज", hint="t____"),
                        VocabItem("tomorrow", "कल (आने वाला)", hint="t______"),
                        VocabItem("yesterday", "कल (बीता हुआ)", hint="y________"),
                        VocabItem("hour", "घंटा", hint="h___"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="What time is it now?",
                            source="अभी क्या समय हुआ है?",
                            words=["What", "time", "is", "it", "now"],
                            blank_word="time",
                            blank_before="What",
                            blank_after="is it now?",
                        ),
                        SentenceItem(
                            target="Today is Monday.",
                            source="आज सोमवार है।",
                            words=["Today", "is", "Monday"],
                        ),
                        SentenceItem(
                            target="We will meet tomorrow.",
                            source="हम कल मिलेंगे।",
                            words=["We", "will", "meet", "tomorrow"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_expressions",
                    title="Common Expressions",
                    description="Excuse me, no problem, see you soon, take care.",
                    objective="Learner can use everyday social expressions fluently.",
                    difficulty=3,
                    order_index=4,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_time",
                    vocabulary=[
                        VocabItem("Excuse me", "माफ़ कीजिएगा", hint="E_____ m_"),
                        VocabItem("No problem", "कोई बात नहीं", hint="N_ p______"),
                        VocabItem("See you soon", "जल्द मिलते हैं", hint="S__ y__ s___"),
                        VocabItem("Take care", "अपना ख्याल रखना", hint="T___ c___"),
                        VocabItem("Of course", "बिल्कुल", hint="O_ c_____"),
                        VocabItem("Have a nice day", "आपका दिन शुभ हो", hint="H___ a n___ d__"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="Excuse me, can you help me?",
                            source="माफ़ कीजिएगा, क्या आप मेरी मदद कर सकते हैं?",
                            words=["Excuse", "me", "can", "you", "help", "me"],
                            blank_word="Excuse",
                            blank_before="",
                            blank_after="me, can you help me?",
                        ),
                        SentenceItem(
                            target="No problem at all.",
                            source="बिल्कुल कोई बात नहीं।",
                            words=["No", "problem", "at", "all"],
                        ),
                        SentenceItem(
                            target="Have a nice day ahead!",
                            source="आपका आगे का दिन शुभ हो!",
                            words=["Have", "a", "nice", "day", "ahead"],
                        ),
                    ],
                ),
            ],
        ),
        # ─────────────────────────────────────────────────────────────
        # UNIT 4 — Real-World English
        # ─────────────────────────────────────────────────────────────
        UnitSpec(
            id="unit_en_04",
            title="Unit 4: Real-World English",
            description="Navigate shopping, restaurant ordering, transportation, and travel booking.",
            order_index=4,
            skills=[
                SkillSpec(
                    id="skill_en_shopping",
                    title="Shopping",
                    description="Price, buy, cost, discount, size, receipt.",
                    objective="Learner can inquire about prices, sizes, and purchase items.",
                    difficulty=4,
                    order_index=1,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_expressions",
                    vocabulary=[
                        VocabItem("buy", "खरीदना", hint="b__"),
                        VocabItem("cost / price", "कीमत", hint="c___"),
                        VocabItem("discount", "छूट", hint="d_______"),
                        VocabItem("size", "आकार/साइज़", hint="s___"),
                        VocabItem("receipt", "रसीद", hint="r______"),
                        VocabItem("cash", "नकद", hint="c___"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="How much does this cost?",
                            source="इसकी कीमत कितनी है?",
                            words=["How", "much", "does", "this", "cost"],
                            blank_word="cost",
                            blank_before="How much does this",
                            blank_after="?",
                        ),
                        SentenceItem(
                            target="Can I get a discount?",
                            source="क्या मुझे छूट मिल सकती है?",
                            words=["Can", "I", "get", "a", "discount"],
                        ),
                        SentenceItem(
                            target="I will pay with cash.",
                            source="मैं नकद भुगतान करूँगा।",
                            words=["I", "will", "pay", "with", "cash"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_restaurants",
                    title="Restaurants",
                    description="Menu, order, bill, water, dish, delicious.",
                    objective="Learner can order a meal, request items, and ask for the bill.",
                    difficulty=4,
                    order_index=2,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_shopping",
                    vocabulary=[
                        VocabItem("menu", "मेनू", hint="m___"),
                        VocabItem("order", "ऑर्डर करना", hint="o____"),
                        VocabItem("bill / check", "बिल", hint="b___"),
                        VocabItem("dish", "व्यंजन", hint="d___"),
                        VocabItem("delicious", "स्वादिष्ट", hint="d________"),
                        VocabItem("waiter", "वेटर", hint="w_____"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="Can we see the menu please?",
                            source="क्या हम कृपया मेनू देख सकते हैं?",
                            words=["Can", "we", "see", "the", "menu", "please"],
                            blank_word="menu",
                            blank_before="Can we see the",
                            blank_after="please?",
                        ),
                        SentenceItem(
                            target="I would like to order pasta.",
                            source="मैं पास्ता ऑर्डर करना चाहूँगा।",
                            words=["I", "would", "like", "to", "order", "pasta"],
                        ),
                        SentenceItem(
                            target="Could we have the bill, please?",
                            source="क्या हमें बिल मिल सकता है, कृपया?",
                            words=["Could", "we", "have", "the", "bill", "please"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_transport",
                    title="Transportation",
                    description="Bus, train, taxi, ticket, station, stop.",
                    objective="Learner can purchase transit tickets and ask about schedules.",
                    difficulty=4,
                    order_index=3,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_restaurants",
                    vocabulary=[
                        VocabItem("bus", "बस", hint="b__"),
                        VocabItem("train", "ट्रेन", hint="t____"),
                        VocabItem("taxi", "टैक्सी", hint="t___"),
                        VocabItem("ticket", "टिकट", hint="t_____"),
                        VocabItem("station", "स्टेशन", hint="s______"),
                        VocabItem("stop", "स्टॉप", hint="s___"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="Where is the bus stop?",
                            source="बस स्टॉप कहाँ है?",
                            words=["Where", "is", "the", "bus", "stop"],
                            blank_word="bus",
                            blank_before="Where is the",
                            blank_after="stop?",
                        ),
                        SentenceItem(
                            target="I need two tickets for the train.",
                            source="मुझे ट्रेन की दो टिकटें चाहिए।",
                            words=["I", "need", "two", "tickets", "for", "the", "train"],
                        ),
                        SentenceItem(
                            target="Call a taxi for me.",
                            source="मेरे लिए एक टैक्सी बुलाएँ।",
                            words=["Call", "a", "taxi", "for", "me"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_travel",
                    title="Travel",
                    description="Airport, flight, passport, luggage, hotel, booking.",
                    objective="Learner can handle international airport and hotel check-in tasks.",
                    difficulty=4,
                    order_index=4,
                    xp_reward=20,
                    prerequisite_skill_id="skill_en_transport",
                    vocabulary=[
                        VocabItem("airport", "हवाई अड्डा", hint="a______"),
                        VocabItem("flight", "उड़ान/फ़्लाइट", hint="f_____"),
                        VocabItem("passport", "पासपोर्ट", hint="p________"),
                        VocabItem("luggage", "सामान", hint="l______"),
                        VocabItem("hotel", "होटल", hint="h____"),
                        VocabItem("booking", "बुकिंग", hint="b______"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="Here is my passport and ticket.",
                            source="यह मेरा पासपोर्ट और टिकट है।",
                            words=["Here", "is", "my", "passport", "and", "ticket"],
                            blank_word="passport",
                            blank_before="Here is my",
                            blank_after="and ticket.",
                        ),
                        SentenceItem(
                            target="What time is our flight departing?",
                            source="हमारी फ़्लाइट कितने बजे रवाना हो रही है?",
                            words=["What", "time", "is", "our", "flight", "departing"],
                        ),
                        SentenceItem(
                            target="I have a hotel booking.",
                            source="मेरी होटल की बुकिंग है।",
                            words=["I", "have", "a", "hotel", "booking"],
                        ),
                    ],
                ),
            ],
        ),
        # ─────────────────────────────────────────────────────────────
        # UNIT 5 — Social English
        # ─────────────────────────────────────────────────────────────
        UnitSpec(
            id="unit_en_05",
            title="Unit 5: Social English",
            description="Discuss hobbies, friendships, workplace & study environments, and express personal opinions.",
            order_index=5,
            skills=[
                SkillSpec(
                    id="skill_en_hobbies",
                    title="Hobbies",
                    description="Music, sports, reading, travel, gaming, cooking.",
                    objective="Learner can talk about interests, activities, and free time.",
                    difficulty=5,
                    order_index=1,
                    xp_reward=25,
                    prerequisite_skill_id="skill_en_travel",
                    vocabulary=[
                        VocabItem("music", "संगीत", hint="m____"),
                        VocabItem("sports", "खेल", hint="s_____"),
                        VocabItem("reading", "पढ़ना", hint="r______"),
                        VocabItem("traveling", "यात्रा करना", hint="t________"),
                        VocabItem("gaming", "गेमिंग", hint="g_____"),
                        VocabItem("cooking", "खाना बनाना", hint="c______"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I love listening to music.",
                            source="मुझे संगीत सुनना पसंद है।",
                            words=["I", "love", "listening", "to", "music"],
                            blank_word="music",
                            blank_before="I love listening to",
                            blank_after=".",
                        ),
                        SentenceItem(
                            target="Playing cricket is my favorite hobby.",
                            source="क्रिकेट खेलना मेरा पसंदीदा शगल है।",
                            words=["Playing", "cricket", "is", "my", "favorite", "hobby"],
                        ),
                        SentenceItem(
                            target="She enjoys reading books.",
                            source="उसे किताबें पढ़ना पसंद है।",
                            words=["She", "enjoys", "reading", "books"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_friends",
                    title="Friends",
                    description="Friendship, gather, share, conversation, hang out.",
                    objective="Learner can invite friends, plan social gatherings, and share stories.",
                    difficulty=5,
                    order_index=2,
                    xp_reward=25,
                    prerequisite_skill_id="skill_en_hobbies",
                    vocabulary=[
                        VocabItem("friendship", "दोस्ती", hint="f_________"),
                        VocabItem("gather", "इकट्ठा होना", hint="g_____"),
                        VocabItem("share", "साझा करना", hint="s____"),
                        VocabItem("hang out", "साथ समय बिताना", hint="h___ o__"),
                        VocabItem("conversation", "बातचीत", hint="c___________"),
                        VocabItem("party", "पार्टी", hint="p____"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="Let's hang out this weekend.",
                            source="चलो इस सप्ताहांत साथ समय बिताते हैं।",
                            words=["Let's", "hang", "out", "this", "weekend"],
                            blank_word="hang",
                            blank_before="Let's",
                            blank_after="out this weekend.",
                        ),
                        SentenceItem(
                            target="We shared funny stories.",
                            source="हमने मज़ाकिया कहानियाँ साझा कीं।",
                            words=["We", "shared", "funny", "stories"],
                        ),
                        SentenceItem(
                            target="True friendship is very valuable.",
                            source="सच्ची दोस्ती बहुत कीमती होती है।",
                            words=["True", "friendship", "is", "very", "valuable"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_work",
                    title="Work & Study",
                    description="Office, project, meeting, exam, homework, university.",
                    objective="Learner can converse about work tasks and educational pursuits.",
                    difficulty=5,
                    order_index=3,
                    xp_reward=25,
                    prerequisite_skill_id="skill_en_friends",
                    vocabulary=[
                        VocabItem("office", "कार्यालय/ऑफ़िस", hint="o_____"),
                        VocabItem("project", "परियोजना/प्रोजेक्ट", hint="p______"),
                        VocabItem("meeting", "बैठक/मीटिंग", hint="m______"),
                        VocabItem("exam", "परीक्षा", hint="e___"),
                        VocabItem("homework", "गृहकार्य", hint="h_______"),
                        VocabItem("university", "विश्वविद्यालय", hint="u_________"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I have an important meeting today.",
                            source="आज मेरी एक महत्वपूर्ण बैठक है।",
                            words=["I", "have", "an", "important", "meeting", "today"],
                            blank_word="meeting",
                            blank_before="I have an important",
                            blank_after="today.",
                        ),
                        SentenceItem(
                            target="She studies at the university.",
                            source="वह विश्वविद्यालय में पढ़ाई करती है।",
                            words=["She", "studies", "at", "the", "university"],
                        ),
                        SentenceItem(
                            target="We completed our project on time.",
                            source="हमने अपना प्रोजेक्ट समय पर पूरा किया।",
                            words=["We", "completed", "our", "project", "on", "time"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_opinions",
                    title="Opinions",
                    description="I think, I believe, agree, disagree, perspective.",
                    objective="Learner can express personal opinions and politely agree/disagree.",
                    difficulty=5,
                    order_index=4,
                    xp_reward=25,
                    prerequisite_skill_id="skill_en_work",
                    vocabulary=[
                        VocabItem("I think", "मुझे लगता है", hint="I t____"),
                        VocabItem("I believe", "मेरा मानना है", hint="I b______"),
                        VocabItem("agree", "सहमत होना", hint="a____"),
                        VocabItem("disagree", "असहमत होना", hint="d________"),
                        VocabItem("opinion", "राय", hint="o______"),
                        VocabItem("useful", "उपयोगी", hint="u_____"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I think this idea is great.",
                            source="मुझे लगता है यह विचार बहुत बढ़िया है।",
                            words=["I", "think", "this", "idea", "is", "great"],
                            blank_word="think",
                            blank_before="I",
                            blank_after="this idea is great.",
                        ),
                        SentenceItem(
                            target="I completely agree with you.",
                            source="मैं आपकी बात से पूरी तरह सहमत हूँ।",
                            words=["I", "completely", "agree", "with", "you"],
                        ),
                        SentenceItem(
                            target="In my opinion, practice is key.",
                            source="मेरी राय में, अभ्यास ही कुंजी है।",
                            words=["In", "my", "opinion", "practice", "is", "key"],
                        ),
                    ],
                ),
            ],
        ),
        # ─────────────────────────────────────────────────────────────
        # UNIT 6 — Practical English
        # ─────────────────────────────────────────────────────────────
        UnitSpec(
            id="unit_en_06",
            title="Unit 6: Practical English",
            description="Discuss health issues, modern technology, financial transactions, and public services.",
            order_index=6,
            skills=[
                SkillSpec(
                    id="skill_en_health",
                    title="Health",
                    description="Doctor, medicine, fever, pain, healthy, exercise.",
                    objective="Learner can explain symptoms and seek medical assistance.",
                    difficulty=6,
                    order_index=1,
                    xp_reward=25,
                    prerequisite_skill_id="skill_en_opinions",
                    vocabulary=[
                        VocabItem("doctor", "डॉक्टर", hint="d_____"),
                        VocabItem("medicine", "दवा", hint="m_______"),
                        VocabItem("fever", "बुखार", hint="f____"),
                        VocabItem("pain", "दर्द", hint="p___"),
                        VocabItem("healthy", "स्वस्थ", hint="h______"),
                        VocabItem("exercise", "व्यायाम", hint="e_______"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I need to see a doctor.",
                            source="मुझे डॉक्टर को दिखाने की ज़रूरत है।",
                            words=["I", "need", "to", "see", "a", "doctor"],
                            blank_word="doctor",
                            blank_before="I need to see a",
                            blank_after=".",
                        ),
                        SentenceItem(
                            target="Take this medicine twice a day.",
                            source="यह दवा दिन में दो बार लें।",
                            words=["Take", "this", "medicine", "twice", "a", "day"],
                        ),
                        SentenceItem(
                            target="Daily exercise keeps you healthy.",
                            source="दैनिक व्यायाम आपको स्वस्थ रखता है।",
                            words=["Daily", "exercise", "keeps", "you", "healthy"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_tech",
                    title="Technology",
                    description="Phone, computer, internet, email, password, software.",
                    objective="Learner can navigate technology terms and digital communication.",
                    difficulty=6,
                    order_index=2,
                    xp_reward=25,
                    prerequisite_skill_id="skill_en_health",
                    vocabulary=[
                        VocabItem("phone", "फ़ोन", hint="p____"),
                        VocabItem("computer", "कंप्यूटर", hint="c_______"),
                        VocabItem("internet", "इंटरनेट", hint="i_______"),
                        VocabItem("email", "ईमेल", hint="e____"),
                        VocabItem("password", "पासवर्ड", hint="p_______"),
                        VocabItem("software", "सॉफ़्टवेयर", hint="s_______"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="Please send me an email.",
                            source="कृपया मुझे एक ईमेल भेजें।",
                            words=["Please", "send", "me", "an", "email"],
                            blank_word="email",
                            blank_before="Please send me an",
                            blank_after=".",
                        ),
                        SentenceItem(
                            target="The internet is running fast.",
                            source="इंटरनेट तेज़ चल रहा है।",
                            words=["The", "internet", "is", "running", "fast"],
                        ),
                        SentenceItem(
                            target="Do not share your password.",
                            source="अपना पासवर्ड साझा न करें।",
                            words=["Do", "not", "share", "your", "password"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_money",
                    title="Money",
                    description="Bank, account, transfer, card, loan, savings.",
                    objective="Learner can discuss banking, card transactions, and finances.",
                    difficulty=6,
                    order_index=3,
                    xp_reward=25,
                    prerequisite_skill_id="skill_en_tech",
                    vocabulary=[
                        VocabItem("bank", "बैंक", hint="b___"),
                        VocabItem("account", "खाता", hint="a______"),
                        VocabItem("transfer", "ट्रांसफ़र", hint="t_______"),
                        VocabItem("card", "कार्ड", hint="c___"),
                        VocabItem("loan", "ऋण/लोन", hint="l___"),
                        VocabItem("savings", "बचत", hint="s______"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I want to open a bank account.",
                            source="मैं एक बैंक खाता खोलना चाहता हूँ।",
                            words=["I", "want", "to", "open", "a", "bank", "account"],
                            blank_word="account",
                            blank_before="I want to open a bank",
                            blank_after=".",
                        ),
                        SentenceItem(
                            target="Can I pay by credit card?",
                            source="क्या मैं क्रेडिट कार्ड से भुगतान कर सकता हूँ?",
                            words=["Can", "I", "pay", "by", "credit", "card"],
                        ),
                        SentenceItem(
                            target="Saving money is good for the future.",
                            source="पैसे बचाना भविष्य के लिए अच्छा है।",
                            words=["Saving", "money", "is", "good", "for", "the", "future"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_services",
                    title="Services",
                    description="Post office, police, emergency, repair, customer care.",
                    objective="Learner can interact with public utility and emergency services.",
                    difficulty=6,
                    order_index=4,
                    xp_reward=25,
                    prerequisite_skill_id="skill_en_money",
                    vocabulary=[
                        VocabItem("post office", "डाकघर", hint="p___ o_____"),
                        VocabItem("police", "पुलिस", hint="p_____"),
                        VocabItem("emergency", "आपातकाल", hint="e________"),
                        VocabItem("repair", "मरम्मत", hint="r_____"),
                        VocabItem("customer care", "ग्राहक सेवा", hint="c_______ c___"),
                        VocabItem("help", "मदद", hint="h___"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="Call emergency services immediately.",
                            source="तुरंत आपातकालीन सेवाओं को कॉल करें।",
                            words=["Call", "emergency", "services", "immediately"],
                            blank_word="emergency",
                            blank_before="Call",
                            blank_after="services immediately.",
                        ),
                        SentenceItem(
                            target="Where is the post office?",
                            source="डाकघर कहाँ है?",
                            words=["Where", "is", "the", "post", "office"],
                        ),
                        SentenceItem(
                            target="Customer care helped me resolve the issue.",
                            source="ग्राहक सेवा ने मेरी समस्या सुलझाने में मदद की।",
                            words=["Customer", "care", "helped", "me", "resolve", "the", "issue"],
                        ),
                    ],
                ),
            ],
        ),
        # ─────────────────────────────────────────────────────────────
        # UNIT 7 — Grammar & Fluency
        # ─────────────────────────────────────────────────────────────
        UnitSpec(
            id="unit_en_07",
            title="Unit 7: Grammar & Fluency",
            description="Master tenses (past/future), comparative forms, and complex sentence connectors.",
            order_index=7,
            skills=[
                SkillSpec(
                    id="skill_en_past",
                    title="Past Tense",
                    description="Simple past & past continuous: went, ate, saw, was doing.",
                    objective="Learner can accurately describe past events and completed stories.",
                    difficulty=7,
                    order_index=1,
                    xp_reward=30,
                    prerequisite_skill_id="skill_en_services",
                    vocabulary=[
                        VocabItem("went", "गया/गई", hint="w___"),
                        VocabItem("ate", "खाया", hint="a__"),
                        VocabItem("saw", "देखा", hint="s__"),
                        VocabItem("bought", "खरीदा", hint="b_____"),
                        VocabItem("was reading", "पढ़ रहा था", hint="w__ r______"),
                        VocabItem("yesterday", "कल", hint="y________"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I went to the market yesterday.",
                            source="मैं कल बाज़ार गया था।",
                            words=["I", "went", "to", "the", "market", "yesterday"],
                            blank_word="went",
                            blank_before="I",
                            blank_after="to the market yesterday.",
                        ),
                        SentenceItem(
                            target="She ate dinner with her family.",
                            source="उसने अपने परिवार के साथ खाना खाया।",
                            words=["She", "ate", "dinner", "with", "her", "family"],
                        ),
                        SentenceItem(
                            target="They bought a new house last year.",
                            source="उन्होंने पिछले साल एक नया घर खरीदा।",
                            words=["They", "bought", "a", "new", "house", "last", "year"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_future",
                    title="Future Tense",
                    description="Will, going to, plans, upcoming events.",
                    objective="Learner can express future plans, promises, and predictions.",
                    difficulty=7,
                    order_index=2,
                    xp_reward=30,
                    prerequisite_skill_id="skill_en_past",
                    vocabulary=[
                        VocabItem("will go", "जाऊँगा/जाऊँगी", hint="w___ g_"),
                        VocabItem("will travel", "यात्रा करूँगा", hint="w___ t_____"),
                        VocabItem("going to", "करने जा रहा हूँ", hint="g____ t_"),
                        VocabItem("tomorrow", "कल", hint="t______"),
                        VocabItem("next week", "अगले हफ़्ते", hint="n___ w___"),
                        VocabItem("future", "भविष्य", hint="f_____"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I will travel to Delhi next week.",
                            source="मैं अगले हफ़्ते दिल्ली की यात्रा करूँगा।",
                            words=["I", "will", "travel", "to", "Delhi", "next", "week"],
                            blank_word="travel",
                            blank_before="I will",
                            blank_after="to Delhi next week.",
                        ),
                        SentenceItem(
                            target="She is going to start a new job.",
                            source="वह एक नई नौकरी शुरू करने जा रही है।",
                            words=["She", "is", "going", "to", "start", "a", "new", "job"],
                        ),
                        SentenceItem(
                            target="We will achieve our goals.",
                            source="हम अपने लक्ष्य हासिल करेंगे।",
                            words=["We", "will", "achieve", "our", "goals"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_comparisons",
                    title="Comparisons",
                    description="Better, faster, bigger, more interesting, best.",
                    objective="Learner can compare qualities, items, and express preferences.",
                    difficulty=7,
                    order_index=3,
                    xp_reward=30,
                    prerequisite_skill_id="skill_en_future",
                    vocabulary=[
                        VocabItem("better", "बेहतर", hint="b_____"),
                        VocabItem("faster", "तेज़", hint="f_____"),
                        VocabItem("bigger", "बड़ा", hint="b_____"),
                        VocabItem("more interesting", "अधिक दिलचस्प", hint="m___ i__________"),
                        VocabItem("best", "सबसे अच्छा", hint="b___"),
                        VocabItem("than", "से (तुलना)", hint="t___"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="This book is better than that one.",
                            source="यह किताब उस किताब से बेहतर है।",
                            words=["This", "book", "is", "better", "than", "that", "one"],
                            blank_word="better",
                            blank_before="This book is",
                            blank_after="than that one.",
                        ),
                        SentenceItem(
                            target="Trains are faster than buses.",
                            source="ट्रेनें बसों से तेज़ होती हैं।",
                            words=["Trains", "are", "faster", "than", "buses"],
                        ),
                        SentenceItem(
                            target="He is the best player on the team.",
                            source="वह टीम का सबसे अच्छा खिलाड़ी है।",
                            words=["He", "is", "the", "best", "player", "on", "the", "team"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_complex",
                    title="Complex Sentences",
                    description="Conjunctions: because, although, however, therefore, while.",
                    objective="Learner can connect thoughts using advanced subordinate clauses.",
                    difficulty=7,
                    order_index=4,
                    xp_reward=30,
                    prerequisite_skill_id="skill_en_comparisons",
                    vocabulary=[
                        VocabItem("because", "क्योंकि", hint="b______"),
                        VocabItem("although", "हालाँकि", hint="a_______"),
                        VocabItem("however", "तथापि", hint="h______"),
                        VocabItem("therefore", "इसलिए", hint="t________"),
                        VocabItem("while", "जबकि", hint="w____"),
                        VocabItem("unless", "जब तक कि नहीं", hint="u_____"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="I stayed home because it was raining.",
                            source="मैं घर पर रहा क्योंकि बारिश हो रही थी।",
                            words=["I", "stayed", "home", "because", "it", "was", "raining"],
                            blank_word="because",
                            blank_before="I stayed home",
                            blank_after="it was raining.",
                        ),
                        SentenceItem(
                            target="Although it was late, he continued working.",
                            source="हालाँकि देर हो चुकी थी, उसने काम जारी रखा।",
                            words=["Although", "it", "was", "late", "he", "continued", "working"],
                        ),
                        SentenceItem(
                            target="Study hard, therefore you will succeed.",
                            source="कड़ी मेहनत से पढ़ाई करो, इसलिए तुम सफल होगे।",
                            words=["Study", "hard", "therefore", "you", "will", "succeed"],
                        ),
                    ],
                ),
            ],
        ),
        # ─────────────────────────────────────────────────────────────
        # UNIT 8 — Conversation Mastery
        # ─────────────────────────────────────────────────────────────
        UnitSpec(
            id="unit_en_08",
            title="Unit 8: Conversation Mastery",
            description="Master small talk, problem solving, narrative storytelling, and fluid discussion.",
            order_index=8,
            skills=[
                SkillSpec(
                    id="skill_en_smalltalk",
                    title="Small Talk",
                    description="Weather, weekend plans, compliments, icebreakers.",
                    objective="Learner can initiate and maintain natural casual conversations.",
                    difficulty=8,
                    order_index=1,
                    xp_reward=35,
                    prerequisite_skill_id="skill_en_complex",
                    vocabulary=[
                        VocabItem("weather", "मौसम", hint="w______"),
                        VocabItem("weekend", "सप्ताहांत", hint="w______"),
                        VocabItem("compliment", "प्रशंसा", hint="c_________"),
                        VocabItem("icebreaker", "बातचीत की शुरुआत", hint="i_________"),
                        VocabItem("pleasant", "सुहावना", hint="p_______"),
                        VocabItem("chat", "गपशप", hint="c___"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="The weather is lovely today, isn't it?",
                            source="आज मौसम कितना सुहावना है, है न?",
                            words=["The", "weather", "is", "lovely", "today", "isn't", "it"],
                            blank_word="weather",
                            blank_before="The",
                            blank_after="is lovely today, isn't it?",
                        ),
                        SentenceItem(
                            target="What are your plans for the weekend?",
                            source="सप्ताहांत के लिए आपकी क्या योजनाएं हैं?",
                            words=["What", "are", "your", "plans", "for", "the", "weekend"],
                        ),
                        SentenceItem(
                            target="It was great chatting with you.",
                            source="आपसे बातचीत करके बहुत अच्छा लगा।",
                            words=["It", "was", "great", "chatting", "with", "you"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_problems",
                    title="Problem Solving",
                    description="Conflict resolution, advice, solutions, negotiate.",
                    objective="Learner can discuss difficulties, propose solutions, and negotiate.",
                    difficulty=8,
                    order_index=2,
                    xp_reward=35,
                    prerequisite_skill_id="skill_en_smalltalk",
                    vocabulary=[
                        VocabItem("solution", "समाधान", hint="s_______"),
                        VocabItem("advice", "सलाह", hint="a_____"),
                        VocabItem("negotiate", "बातचीत करके हल निकालना", hint="n________"),
                        VocabItem("resolve", "सुलझाना", hint="r______"),
                        VocabItem("issue", "मुद्दा/समस्या", hint="i____"),
                        VocabItem("suggest", "सुझाव देना", hint="s______"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="We need to find a solution together.",
                            source="हमें मिलकर एक समाधान ढूंढने की ज़रूरत है।",
                            words=["We", "need", "to", "find", "a", "solution", "together"],
                            blank_word="solution",
                            blank_before="We need to find a",
                            blank_after="together.",
                        ),
                        SentenceItem(
                            target="What do you suggest we do?",
                            source="आप क्या सुझाव देते हैं कि हम क्या करें?",
                            words=["What", "do", "you", "suggest", "we", "do"],
                        ),
                        SentenceItem(
                            target="I appreciate your helpful advice.",
                            source="मैं आपकी मददगार सलाह की सराहना करता हूँ।",
                            words=["I", "appreciate", "your", "helpful", "advice"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_storytelling",
                    title="Storytelling",
                    description="Narrative flow: first, then, suddenly, finally, experience.",
                    objective="Learner can construct engaging narratives and personal stories.",
                    difficulty=8,
                    order_index=3,
                    xp_reward=35,
                    prerequisite_skill_id="skill_en_problems",
                    vocabulary=[
                        VocabItem("first", "पहले", hint="f____"),
                        VocabItem("then", "फिर", hint="t___"),
                        VocabItem("suddenly", "अचानक", hint="s_______"),
                        VocabItem("finally", "अंत में", hint="f______"),
                        VocabItem("experience", "अनुभव", hint="e_________"),
                        VocabItem("memorable", "यादगार", hint="m________"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="Suddenly, everything changed for the better.",
                            source="अचानक सब कुछ बेहतरी के लिए बदल गया।",
                            words=["Suddenly", "everything", "changed", "for", "the", "better"],
                            blank_word="Suddenly",
                            blank_before="",
                            blank_after=", everything changed for the better.",
                        ),
                        SentenceItem(
                            target="First we traveled to Paris, then to Rome.",
                            source="पहले हमने पेरिस की यात्रा की, फिर रोम की।",
                            words=["First", "we", "traveled", "to", "Paris", "then", "to", "Rome"],
                        ),
                        SentenceItem(
                            target="It was a truly memorable experience.",
                            source="यह वाकई एक बेहद यादगार अनुभव था।",
                            words=["It", "was", "a", "truly", "memorable", "experience"],
                        ),
                    ],
                ),
                SkillSpec(
                    id="skill_en_advanced",
                    title="Advanced Conversation",
                    description="Nuance, debate, idiom, fluent expression, abstract thought.",
                    objective="Learner can engage in nuanced debates and express complex abstract ideas fluently.",
                    difficulty=8,
                    order_index=4,
                    xp_reward=40,
                    prerequisite_skill_id="skill_en_storytelling",
                    vocabulary=[
                        VocabItem("nuance", "बारीकी", hint="n_____"),
                        VocabItem("fluent", "धाराप्रवाह", hint="f_____"),
                        VocabItem("perspective", "दृष्टिकोण", hint="p__________"),
                        VocabItem("abstract", "अमूर्त", hint="a_______"),
                        VocabItem("eloquent", "प्रभावशाली", hint="e_______"),
                        VocabItem("mastery", "महारत", hint="m______"),
                    ],
                    sentences=[
                        SentenceItem(
                            target="She spoke with great eloquence and confidence.",
                            source="वह बड़े ही प्रभावशाली और आत्मविश्वास के साथ बोलीं।",
                            words=["She", "spoke", "with", "great", "eloquent", "eloquence", "and", "confidence"],
                            blank_word="eloquence",
                            blank_before="She spoke with great",
                            blank_after="and confidence.",
                        ),
                        SentenceItem(
                            target="From my perspective, continuous learning leads to mastery.",
                            source="मेरे दृष्टिकोण से, निरंतर सीखना ही महारत की ओर ले जाता है।",
                            words=["From", "my", "perspective", "continuous", "learning", "leads", "to", "mastery"],
                        ),
                        SentenceItem(
                            target="Congratulations on achieving English fluency!",
                            source="अंग्रेज़ी धाराप्रवाहता हासिल करने पर बधाई!",
                            words=["Congratulations", "on", "achieving", "English", "fluency"],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
