apiVersion: v1
kind: Service
metadata:
  name: duolingo-backend-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: duolingo-backend
---
apiVersion: v1
kind: Service
metadata:
  name: duolingo-frontend-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: duolingo-frontend
